language: android
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - develop

before_install:
  - date
  - ./envsetup 1> /dev/null 2%>1
  - cd $TRAVIS_BUILD_DIR
  - cd tools/travis-ci
  - sh setupNDK.sh
  - export PATH=`pwd`/android-ndk:$PATH
  - echo $PATH
  - cd $TRAVIS_BUILD_DIR
script:
  - cd $TRAVIS_BUILD_DIR
  - ndk-build -j8
after_script:
  - date
